apiVersion: v1
kind: Pod
metadata:
  name: ssh-network-tools
  labels:
    app: ssh-network-tools
spec:
  containers:
    - name: sshd
      image: magickatt/ssh-network-tools:latest
      ports:
        - containerPort: 22
---
apiVersion: v1
kind: Service
metadata:
  name: ssh-network-tools
  labels:
    app: ssh-network-tools
spec:
  ports:
    - name: ssh
      port: 22
      protocol: "TCP"
      targetPort: 22
  selector:
    app: ssh-network-tools
  type: LoadBalancer
